name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pip install pylint
        pylint --disable=unnecessary-lambda-assignment \
               --disable=missing-final-newline \
               --disable=missing-function-docstring \
               --disable=invalid-name \
               --disable=no-else-return \
               --disable=unused-argument \
               --disable=useless-return \
               --disable=use-implicit-booleaness-not-comparison \
               --max-line-length=100 \
               --disable=fixme $(git ls-files '*.py')
